#!/usr/bin/env bash
# Hubra Vaults Rebalancer - Docker Setup
# 
# This script sets up the complete Docker-based rebalancer infrastructure:
# - Builds container images
# - Generates vaults.yaml from .env-* files
# - Starts all rebalancer containers + monitoring stack
# - Installs CLI helper scripts
#
# Usage: sudo bash deploy/setup.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log() { echo -e "${GREEN}===${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ── 1. Check prerequisites ─────────────────────────────────
log "Checking prerequisites..."

if [[ $EUID -ne 0 ]]; then
  error "Run as root: sudo bash $0"
fi

# Install Docker if not present
if ! command -v docker &> /dev/null; then
  log "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
  log "Docker installed"
else
  echo "  Docker: $(docker --version)"
fi

# Check docker compose
if ! docker compose version &> /dev/null; then
  error "Docker Compose V2 not found. Please update Docker."
fi
echo "  Docker Compose: $(docker compose version --short)"

# ── 2. Discover vault instances ────────────────────────────
log "Discovering vault instances..."
cd "$REPO_DIR"

mapfile -t instances < <(find . -maxdepth 1 -name '.env-*' -printf '%f\n' | sed 's/^\.env-//' | sort)

if [[ ${#instances[@]} -eq 0 ]]; then
  error "No .env-* files found. Create .env-usdc, .env-usdt, etc. from .env.example"
fi

echo "  Found ${#instances[@]} vaults: ${instances[*]}"

# ── 3. Generate vaults.yaml from .env-* files ──────────────
log "Generating config/vaults.yaml..."

mkdir -p config

cat > config/vaults.yaml <<YAML
# Hubra Vaults Configuration
# Auto-generated by setup.sh on $(date -Iseconds)
#
# To add a new vault:
# 1. Create .env-{symbol} file
# 2. Create {symbol}-strategies.json
# 3. Run: sudo bash deploy/setup.sh

idle_threshold: 10.00
voltr_api: https://api.voltr.xyz

vaults:
YAML

for inst in "${instances[@]}"; do
  env_file=".env-${inst}"
  
  # Extract values from env file
  SYMBOL=$(grep -oP '(?<=ASSET_SYMBOL=).*' "$env_file" 2>/dev/null || echo "$inst")
  ADDRESS=$(grep -oP '(?<=VOLTR_VAULT_ADDRESS=).*' "$env_file" 2>/dev/null || echo "")
  
  if [[ -z "$ADDRESS" ]]; then
    warn "No VOLTR_VAULT_ADDRESS in $env_file, skipping..."
    continue
  fi
  
  # Convert to lowercase for container name
  inst_lower=$(echo "$inst" | tr '[:upper:]' '[:lower:]')
  
  cat >> config/vaults.yaml <<YAML
  - symbol: ${SYMBOL^^}
    name: Hubra Copilot ${SYMBOL^^}
    address: ${ADDRESS}
    rebalancer_host: rebalancer-${inst_lower}
    rebalancer_port: 9090

YAML

  echo "  Added ${SYMBOL^^} (${ADDRESS:0:8}...)"
done

# ── 4. Generate docker-compose.yml with discovered vaults ──
log "Generating docker-compose.yml..."

cat > docker-compose.yml <<'COMPOSE'
# Hubra Vaults Rebalancer - Docker Compose
# Auto-generated by setup.sh

version: "3.8"

networks:
  hubra-vaults:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

x-rebalancer-common: &rebalancer-common
  build: .
  restart: unless-stopped
  networks:
    - hubra-vaults
  healthcheck:
    test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/health"]
    interval: 30s
    timeout: 10s
    retries: 3

services:
COMPOSE

# Add rebalancer services
for inst in "${instances[@]}"; do
  inst_lower=$(echo "$inst" | tr '[:upper:]' '[:lower:]')
  SYMBOL=$(grep -oP '(?<=ASSET_SYMBOL=).*' ".env-${inst}" 2>/dev/null || echo "$inst")
  ADDRESS=$(grep -oP '(?<=VOLTR_VAULT_ADDRESS=).*' ".env-${inst}" 2>/dev/null || echo "unknown")
  
  # Check if strategies file exists
  strategies_file="${inst_lower}-strategies.json"
  if [[ ! -f "$strategies_file" ]]; then
    strategies_file="strategies.json"
  fi
  
  cat >> docker-compose.yml <<COMPOSE

  rebalancer-${inst_lower}:
    <<: *rebalancer-common
    container_name: rebalancer-${inst_lower}
    env_file: .env-${inst}
    environment:
      - STRATEGIES_FILE=/app/strategies.json
    volumes:
      - ./${strategies_file}:/app/strategies.json:ro
    labels:
      - "hubra.rebalancer=true"
      - "hubra.vault.symbol=${SYMBOL^^}"
      - "hubra.vault.address=${ADDRESS}"
COMPOSE

  echo "  Added rebalancer-${inst_lower}"
done

# Add monitor and monitoring stack
cat >> docker-compose.yml <<'COMPOSE'

  # ============================================
  # MONITOR SERVICE
  # ============================================

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: hubra-monitor
    restart: unless-stopped
    networks:
      - hubra-vaults
    volumes:
      - ./config/vaults.yaml:/app/config/vaults.yaml:ro
    environment:
      - VAULTS_CONFIG=/app/config/vaults.yaml
      - CHECK_INTERVAL=300
    depends_on:
COMPOSE

# Add depends_on for monitor
for inst in "${instances[@]}"; do
  inst_lower=$(echo "$inst" | tr '[:upper:]' '[:lower:]')
  echo "      - rebalancer-${inst_lower}" >> docker-compose.yml
done

cat >> docker-compose.yml <<'COMPOSE'

  # ============================================
  # MONITORING STACK
  # ============================================

  prometheus:
    image: prom/prometheus:latest
    container_name: hubra-prometheus
    restart: unless-stopped
    networks:
      - hubra-vaults
    ports:
      - "9091:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:latest
    container_name: hubra-grafana
    restart: unless-stopped
    networks:
      - hubra-vaults
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
COMPOSE

echo "  Added monitor, prometheus, grafana"

# ── 5. Build Docker images ─────────────────────────────────
log "Building Docker images..."
docker compose build --pull

# ── 6. Start all containers ────────────────────────────────
log "Starting containers..."
docker compose up -d

# Wait for containers to be healthy
echo "  Waiting for services to be ready..."
sleep 10

# ── 7. Install CLI helper scripts ──────────────────────────
log "Installing CLI tools..."

install_cli() {
  local name="$1" body="$2"
  local path="/usr/local/bin/hubra-rebalancer-${name}"
  cat > "$path" <<SCRIPT
#!/usr/bin/env bash
set -euo pipefail
REPO_DIR="$REPO_DIR"
cd "\$REPO_DIR"
${body}
SCRIPT
  chmod +x "$path"
  echo "  installed hubra-rebalancer-${name}"
}

install_cli "logs" '
if [[ $# -gt 0 ]]; then
  docker compose logs -f "rebalancer-$1"
else
  docker compose logs -f
fi
'

install_cli "status" '
docker compose ps
'

install_cli "health" '
echo "Checking rebalancer health..."
for container in $(docker compose ps --format "{{.Name}}" | grep rebalancer-); do
  if docker exec "$container" wget -q --spider http://localhost:9090/health 2>/dev/null; then
    echo "  $container: OK"
  else
    echo "  $container: FAIL"
  fi
done
'

install_cli "restart" '
if [[ $# -gt 0 ]]; then
  docker compose restart "rebalancer-$1"
else
  docker compose restart
fi
'

install_cli "stop" '
docker compose down
'

install_cli "start" '
docker compose up -d
'

install_cli "rebuild" '
docker compose build --no-cache
docker compose up -d
'

install_cli "monitor-logs" '
docker compose logs -f monitor
'

# ── 8. Show status ─────────────────────────────────────────
log "Setup complete!"
echo ""
echo "Services:"
docker compose ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}"
echo ""
echo "Endpoints:"
echo "  Grafana     →  http://localhost:3001  (admin/admin)"
echo "  Prometheus  →  http://localhost:9091"
echo ""
echo "CLI tools:"
echo "  hubra-rebalancer-status        # show all container status"
echo "  hubra-rebalancer-logs          # tail all logs"
echo "  hubra-rebalancer-logs usdc     # tail specific rebalancer"
echo "  hubra-rebalancer-monitor-logs  # tail monitor logs"
echo "  hubra-rebalancer-health        # check health endpoints"
echo "  hubra-rebalancer-restart       # restart all"
echo "  hubra-rebalancer-restart usdc  # restart specific"
echo "  hubra-rebalancer-stop          # stop all"
echo "  hubra-rebalancer-start         # start all"
echo "  hubra-rebalancer-rebuild       # rebuild and restart"
echo ""
echo "Adding a new vault:"
echo "  1. Create .env-newvault from .env.example"
echo "  2. Create newvault-strategies.json"
echo "  3. Run: sudo bash deploy/setup.sh"
